const products = [
    {
      id: 0,
      name: "Hawaiian Shirt V1",
      brand: "Zara",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "shirt",
      price: 99.99,
      image: "./img/products/f1.jpg",
      sale: true,
      saleAmount: 20,
      rate: 4,
    },
    {
        id: 1,
        name: "Hawaiian Shirt V2",
        brand: "Zara",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "shirt",
        price: 99.99,
        image: "./img/products/f2.jpg",
        sale: true,
        saleAmount: 25,
        rate: 5
      },
      {
        id: 2,
        name: "Floral Shirt V1",
        brand: "HM",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "shirt",
        price: 99.99,
        image: "./img/products/f3.jpg",
        sale: true,
        saleAmount: 20,
        rate: 3
      },
      {
        id: 3,
        name: "Floral Shirt V2",
        brand: "HM",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "shirt",
        price: 99.99,
        image: "./img/products/f4.jpg",
        // sale: true,
        // saleAmount: 20,
        rate: 5
      },
      {
        id: 4,
        name: "Dark Floral Shirt V3",
        brand: "Reserved",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "shirt",
        price: 99.99,
        image: "./img/products/f5.jpg",
        // sale: true,
        // saleAmount: 20,
        rate: 5
      },
      {
        id: 5,
        name: "Two-tone Jacket",
        brand: "Zara",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "jacket",
        price: 199.99,
        image: "./img/products/f6.jpg",
        // sale: true,
        // saleAmount: 20,
        rate: 5
      },
      {
        id: 6,
        name: "Floral Pants",
        brand: "HM",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "pants",
        price: 120.99,
        image: "./img/products/f7.jpg",
        sale: true,
        saleAmount: 15,
        rate: 4
      },
      {
        id: 7,
        name: "Kitty Longsleeve",
        brand: "Reserved",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "longsleeve",
        price: 64.99,
        image: "./img/products/f8.jpg",
        // sale: true,
        // saleAmount: 20,
        rate: 3
      },
      {
        id: 8,
        name: "Blue Elegant Shirt",
        brand: "Zara",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "shirt",
        price: 139.99,
        image: "./img/products/n1.jpg",
        sale: true,
        saleAmount: 10,
        rate: 5
      },
      {
        id: 9,
        name: "Grey Elegant Shirt",
        brand: "Zara",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "shirt",
        price: 139.99,
        image: "./img/products/n2.jpg",
        // sale: true,
        // saleAmount: 10,
        rate: 5
      },
      {
        id: 10,
        name: "White Elegant Shirt",
        brand: "Zara",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "shirt",
        price: 149.99,
        image: "./img/products/n3.jpg",
        // sale: true,
        // saleAmount: 10,
        rate: 5
      },
      {
        id: 11,
        name: "Moro Short Shirt",
        brand: "Reserved",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "shirt",
        price: 139.99,
        image: "./img/products/n4.jpg",
        sale: true,
        saleAmount: 10,
        rate: 2
      },
      {
        id: 12,
        name: "Jeans Shirt/Jacket",
        brand: "Zara",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "shirt",
        price: 169.99,
        image: "./img/products/n5.jpg",
        sale: true,
        saleAmount: 20,
        rate: 5
      },
      {
        id: 13,
        name: "Light Grey Shorts",
        brand: "Zara",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "shorts",
        price: 89.99,
        image: "./img/products/n6.jpg",
        // sale: true,
        // saleAmount: 10,
        rate: 5
      },
      {
        id: 14,
        name: "Orange Travel Shirt",
        brand: "Zara",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "shirt",
        price: 139.99,
        image: "./img/products/n7.jpg",
        sale: true,
        saleAmount: 10,
        rate: 5
      },
      {
        id: 15,
        name: "Black Short Shirt",
        brand: "HM",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "shirt",
        price: 69.99,
        image: "./img/products/n8.jpg",
        // sale: true,
        // saleAmount: 10,
        rate: 5
      }
];